<table width="98%" border="0" cellspacing="3" cellpadding="3" class="black">
	<tr>
		<td><span class="normalbold">AT&amp;T Wireless<br/></span><strong>Objectives:</strong>
			To build and maintain the AT&amp;T Wireless customer service web application. To create customer-facing UI
			with dynamic, data-driven functionality via JSP/JHTML.<br/><strong>Challenges:</strong>
			To learn very complex development, testing, build and deployment environments. Struggling with some crazy tool configurations to keep my local code happily synched with testing and production code.
			Our MVC development model was a little shaky (as things were with Dynamo and Teamsite in the mix).

		</td>
	</tr>
</table>