<table width="98%" border="0" cellspacing="3" cellpadding="3" class="black">
	<tr>
		<td><span class="normalbold">Group Health Cooperative<br/></span><strong>Objectives:</strong>
			To deliver a dynamic and secure web experience for staff, service partners, and ghc members
			enabling them to make appointments with physicians and specialists, view lab results, and fill
			prescriptions and other integrated services.
			<br/><strong>Challenges:</strong>
			Primary challeges were overcome by
			having a continuous integration environment with TeamSite, TeamCity, Spring, Maven, and a flexible MVC architecture that made building, testing, and deploying applications quickly to all environments.
		</td>
	</tr>
</table>