<table width="98%" border="0" cellspacing="3" cellpadding="3" class="black">
	<tr>
		<td><span class="normalbold">Hilton Hotels &amp; Resorts<br/></span><strong>Objectives:</strong>
			To create 7 distinct, n-tiered, data-driven Web sites (Hilton and its sister sites) with a single code-based but skinned differently by css. <br/>
			<strong>Challenges:</strong>
			To develop, test and deploy each site in an extremely short time frame. To utilize css cascading rules to control
			the visual display of each site without copy/pasting code and markup between sites. To create JSP/JHTML pages with built-in logic and shopping-cart functionality
			to prevent duplicative programming and reduce development time.

		</td>
	</tr>
</table>