<table width="98%" border="0" cellspacing="3" cellpadding="3" class="black">
	<tr>
		<td><span class="normalbold">Microsoft Corp.<br/></span><strong>Objectives:</strong>
			To produce and maintain the Microsoft.com "Executive Circle" website and the "MS InfoWeb"
			Intranet site. To create a working GUI (DHTML pages and working forms) for a partner-developed business mapping tool.
			<br/><strong>Challenges:</strong>
			To overcome incompatibilites between multiple server environments, database configurations,
			and publishing protocols by redesigning development processes and reassigning
			group ownership of several project components.
		</td>
	</tr>
</table>