<table width="98%" border="0" cellspacing="3" cellpadding="3" class="black">
	<tr>
		<td><span class="normalbold">Sotto Wireless<br/></span><strong>Objectives:</strong>
			To give Sottowireless.com a Web site, Storefront, and Activation Portal from the ground up, literally.<br/>
			<strong>Challenges:</strong>
			As with any startup, the main challenge lies in one's ability to change roles at the drop of a hat. As was the case with Sotto, I was tasked to create the db schema, all java servlets, all graphics and flash pieces, as well as
			all client-side scripts and style sheets. Other challenges were in creating and maintaining a fluid development, staging, and production evironments
			using Linux - Apache, Tomcat, MySql servers.
		</td>
	</tr>
</table>