<table width="98%" border="0" cellspacing="3" cellpadding="3" class="black">
	<tr>
		<td><span class="normalbold">Visa<br/></span><strong>Objectives:</strong>
			To build and maintain Visa merchant portals and customer service web applications. To create customer-facing UI
			with dynamic, data-driven functionality via JSP and GSP.<br/><strong>Challenges:</strong>
			To learn very complex development, testing, build and deployment environments. Working in a development and testing
			schedule that had me delivering designs as well as integrated gsp pages. Accommodating changing design specifications
			within a new angular.js development model.

		</td>
	</tr>
</table>